nordic-institute/X-Road-REST-UI

- doc/UseCases/uc-member_x-road_use_case_model_for_member_management.md
- Define new UX requirements
- Define layout
- First implementation should have: 1) a table showing the Clients list; 2) search field; 3) buttons to create new clients and possibility to add Subsystems for each Member
- Propose UI/UX solutions
- UI specs provided seperately
> XRDDEV-266 SS Clients view

- doc/UseCases/uc-ss_x-road_use_case_model_for_security_server_management_1.4_Y-883-4.md
Invision demo: http://gofore.invisionapp.com/share/AQQ7BY1GCKV
> Log-out use cases - 1) user logs out, 2) automatic log-out (30 mins idle user)

- doc/UseCases/uc-member_x-road_use_case_model_for_member_management.md
- created a separate description of the Member Owner detail view and a SS client detail view
- added the Security Server certificate and the action to export it in Internal servers tab
> Xrddev 395 - clients' details views

- src/proxy-ui-api/frontend/nightwatch.json
- src/proxy-ui-api/frontend/tests/e2e/env/globals.js
- src/proxy-ui-api/frontend/tests/e2e/pages/ssFrontPage.js
- src/proxy-ui-api/frontend/tests/e2e/pages/ssMainPage.js
- src/proxy-ui-api/frontend/tests/e2e/specs/ss-login.js
Added initial login end2end tests for the Security Server.
- Logging in with incorrect credentials fails
- Logging in with correct credentials succeeds
- Logged in user remains logged in after refreshing the browser
Issue: https://jira.niis.org/browse/XRDDEV-321
Added also test infrastructure
- Page objects
- Global test config
- Nightwatch config
> XRDDEV-321 Add initial SS end2end tests

- doc/UseCases/uc-service_x-road_use_case_model_for_service_management_1.6_Y-883-3.md
Updated the UC with the REST services.
UI demo: https://gofore.invisionapp.com/project/16962542
> Xrddev 396 - subystems' services details views

- PULL_REQUEST_TEMPLATE.md
> XRDDEV-381 Pull request template

- src/proxy-ui-api/frontend/src/App.vue
- src/proxy-ui-api/frontend/src/components/InternalServers.vue
- src/proxy-ui-api/frontend/src/locales/en.json
- src/proxy-ui-api/frontend/src/store/modules/user.ts
- src/proxy-ui-api/frontend/src/views/Base.vue
- src/proxy-ui-api/frontend/src/views/Login.vue
- Add dialog for the session timeout
- Fix minor font issues
Jira task https://jira.niis.org/browse/XRDDEV-300
Passed jenkins build https://jenkins.niis.org/view/api-based-ui/job/rest-ui-build-feature-branch/25/
> Xrddev 300 auto logout

- src/proxy-ui-api/src/main/resources/openapi-authentication.yaml
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
OpenAPI 3.0 specification improvements. Authentication separated to openapi-authentication.yaml file.
> XRDDEV-283: authentication

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/ClientConverter.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/GlobalConfWrapper.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/ClientsApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/repository/ClientRepository.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ClientService.java
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ClientsApiControllerIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/repository/ClientRepositoryIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/ClientServiceIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/util/TestUtils.java
> XRDDEV-509 Search clients

- doc/Manuals/ig-ss_x-road_v6_security_server_installation_guide.md
- doc/Manuals/ug-syspar_x-road_v6_system_parameters.md
- src/common-util/src/main/java/ee/ria/xroad/common/DefaultFilepaths.java
- src/common-util/src/main/java/ee/ria/xroad/common/SystemProperties.java
- src/packages/src/xroad/common/base/etc/xroad/ssl/openssl.cnf
- src/packages/src/xroad/common/nginx/etc/xroad/nginx/default-xroad.conf
- src/packages/src/xroad/common/proxy-ui-api/etc/xroad/services/proxy-ui-api.conf
- src/packages/src/xroad/common/proxy-ui-api/usr/share/xroad/bin/xroad-proxy-ui-api
- src/packages/src/xroad/common/proxy/usr/share/xroad/db/serverconf-changelog.xml
- src/packages/src/xroad/common/proxy/usr/share/xroad/db/serverconf/8-apikeys.xml
- src/packages/src/xroad/default-configuration/proxy-ui-api-logback.xml
- src/packages/src/xroad/default-configuration/proxy-ui-api.ini
- src/packages/src/xroad/ubuntu/bionic/debian/xroad-proxy-ui-api.service
- src/packages/src/xroad/ubuntu/bionic/debian/xroad-proxy.service
- src/packages/src/xroad/ubuntu/generic/control
- src/packages/src/xroad/ubuntu/generic/xroad-proxy-ui-api.install
- src/packages/src/xroad/ubuntu/generic/xroad-proxy-ui-api.links
- src/packages/src/xroad/ubuntu/generic/xroad-proxy-ui-api.postinst
- src/packages/src/xroad/ubuntu/generic/xroad-proxy-ui-api.preinst
- src/packages/src/xroad/ubuntu/generic/xroad-proxy-ui-api.templates
- src/packages/src/xroad/ubuntu/generic/xroad-proxy.preinst
- src/proxy-ui-api/README.md
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/auth/ApiKeyAuthenticationManager.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/PropertyFileReadingHibernateCustomizer.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/UsernameSettingTransactionManager.java
- src/proxy-ui-api/src/main/resources/application.properties
Please include a summary of the change
> XRDDEV-414 ubuntu packaging

- src/proxy-ui-api/README.md
Please include a summary of the change
> XRDDEV-372 test commit

- src/proxy-ui-api/build.gradle
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/ServiceDescriptionConverter.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/ServiceDescriptionsApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/repository/ServiceDescriptionRepository.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ClientService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ServiceDescriptionService.java
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ClientsApiControllerIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/GroupsApiControllerIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ServiceDescriptionsApiControllerIntegrationTest.java
- src/proxy-ui-api/src/test/resources/data.sql
- src/serverconf/src/main/java/ee/ria/xroad/common/conf/serverconf/dao/ServiceDescriptionDAOImpl.java
https://jira.niis.org/browse/XRDDEV-485
endpoints to enable / disable services
> XRDDEV-485 enable and disable service descriptions

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/ServiceDescriptionsApiController.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ServiceDescriptionsApiControllerIntegrationTest.java
Jenkins build passes: https://jenkins.niis.org/view/api-based-ui/job/rest-ui-build-pull-request/48/
> XRDDEV-485 fix broken build after merge

- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
One more API change for https://jira.niis.org/browse/XRDDEV-575
> XRDDEV-575 add warnings handling for addClient

- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
Format, range, length, example values and more detailed descriptions for the input parameters and responses.
> XRDDEV-430: parameter details

- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
* service descriptions moved under clients api endpoints
* client id and service description id as path parameters
* security category added for services
* improvements in query parameters
* /certificates/{hash}/disable changed to /certificates/{hash}/deactivate
> XRDDEV-394: openapi yaml

- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
getService endpoint and fixes
* added a getService endpoint
* fixed syntax with YamlLinter
* fixed wrong return type (was SecurityServer instead of Service)
> XRDDEV-394 Service descriptions API design // additions and fixes

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/ClientsApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/ServiceDescriptionsApiController.java
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ClientsApiControllerIntegrationTest.java
**¡HOX! Do not merge before** #58 
Updates Service Descriptions and Services API
Only this commit is relevant: https://github.com/nordic-institute/X-Road-REST-UI/commit/33ababa0870ba5c15db12f393723b37712557e30
> XRDDEV-484 & 483 Service Descriptions and Services API

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/ServiceDescriptionsApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ServiceDescriptionService.java
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ServiceDescriptionsApiControllerIntegrationTest.java
- src/serverconf/src/main/resources/serverconf.hbm.xml
Update WSDL URL. Also fixes couple of bugs:
* hibernate mappings that cascaded `delete` from `ServiceType` -> `ServiceDescriptionType` -> `ClientType`. In other words Client got deleted everytime you deleted a ServiceDescription and ServiceDescription got deleted everytime you deleted a Service
* fixes client search regression (search term minimum length can be 0 instead of 1)
> XRDDEV-557 Update WSDL URL + bug fixes

- src/build.gradle
Update dependency check plugin version to fix broken builds
> XRDDEV-600 update dependency-check-gradle

- src/proxy-ui-api/README.md
- src/proxy-ui-api/build.gradle
https://jira.niis.org/browse/XRDDEV-602
> XRDDEV-602 install npm

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/ApiUtil.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/ClientsApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/GroupsApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/repository/ClientRepository.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ClientService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/ServiceDescriptionService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/util/PersistenceUtils.java
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/converter/GroupConverterTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/converter/ServiceConverterTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ClientsApiControllerIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/GroupsApiControllerIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ServiceDescriptionsApiControllerIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/ServicesApiControllerIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/SystemApiControllerTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/repository/ApiKeyRepositoryCachingIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/repository/ApiKeyRepositoryIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/repository/ClientRepositoryIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/ClientServiceIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/service/GroupsServiceIntegrationTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/util/TestUtils.java
https://jira.niis.org/browse/XRDDEV-619
Makes creating resources with POST requests follow a consistent approach and return the created items
PR build (success): https://jenkins.niis.org/view/api-based-ui/job/rest-ui-build-pull-request/72/
> XRDDEV-619 add convention for POST create resources

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
- src/packages/src/xroad/default-configuration/proxy-ui-api-logback.xml
- src/proxy-ui-api/build.gradle
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/auth/ApiKeyAuthenticationManager.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/AddCorrelationIdFilter.java
- src/proxy-ui-api/src/main/resources/application.properties
Rebased version of https://github.com/nordic-institute/X-Road-REST-UI/pull/76
https://jenkins.niis.org/job/rest-ui-build-packages-pipeline/432/
> XRDDEV-406 rebased

- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/ClientConverter.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/Converters.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/GroupConverter.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/SecurityServerConverter.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/converter/ServiceConverter.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/SecurityServersApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/openapi/SystemApiController.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/service/GlobalConfService.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/util/FormatUtils.java
- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/converter/ClientConverterTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/converter/SecurityServerConverterTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/converter/ServiceConverterTest.java
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/SecurityServersApiControllerTest.java
Rebased one to replace https://github.com/nordic-institute/X-Road-REST-UI/pull/81
https://jenkins.niis.org/job/rest-ui-build-packages-pipeline/433/
> XRDDEV-578 rebased

- src/proxy-ui-api-devtools/src/main/resources/application-devtools.properties
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/DatabasePropertiesEnvironmentPostProcessor.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/PropertyFileReadingEnvironmentPostProcessor.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/PropertyFileReadingHibernateCustomizer.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/SslPropertiesEnvironmentPostProcessor.java
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/UsernameSettingTransactionManager.java
- src/proxy-ui-api/src/main/resources/META-INF/spring-devtools.properties
- src/proxy-ui-api/src/main/resources/application.properties
- src/proxy-ui-api/src/test/java/org/niis/xroad/restapi/openapi/SystemApiControllerTest.java
https://jira.niis.org/browse/XRDDEV-674
Also fixes broken devtools / hotdeploy configuration https://confluence.niis.org/display/XRDDEV/Hot+swapping+with+Spring+devtools
> XRDDEV-674 fix tests wipeout db

- src/proxy-ui-api/src/main/resources/openapi-definition.yaml
https://jira.niis.org/browse/XRDDEV-679
https://jenkins.niis.org/view/api-based-ui/job/rest-ui-build-pull-request/96/
> XRDDEV-679 fix validation errors

- src/packages/src/xroad/common/nginx/etc/xroad/nginx/default-xroad.conf
Changed Proxy port back to 5000 since the new Proxy UI API should be in 4000
Jenkins build passes: https://jenkins.niis.org/view/api-based-ui/job/rest-ui-build-feature-branch/82/console
> Change Proxy port back to 5000

- src/proxy-ui-api/frontend/src/components/CertificateOcsp.vue
- src/proxy-ui-api/frontend/src/components/CertificateStatus.vue
Fix for linter errors in previous XRDDEV-631 PR
Succesfull build: 
https://jenkins.niis.org/view/api-based-ui/job/rest-ui-build-pull-request/106/console
> XRDDEV-631 Quick fix for linter errors

- doc/Manuals/ug-ss_x-road_6_security_server_user_guide.md
- src/proxy-ui-api/build.gradle
- src/proxy-ui-api/src/main/java/org/niis/xroad/restapi/config/IpThrottlingFilter.java
- src/proxy-ui-api/src/main/resources/common-application.properties
https://jira.niis.org/browse/XRDDEV-431
jenkins: https://jenkins.niis.org/view/api-based-ui/job/rest-ui-build-pull-request/123/
- to [tracking table in Confluence](https://confluence.niis.org/display/XRDDEV/Accepted+npm+audit+vulnerabilities)
- to [audit-resolve.json](https://confluence.niis.org/display/XRDDEV/Front-end+build+process#Front-endbuildprocess-Resolvingauditfailures) file in version control
- you have crosschecked that these match
> XRDDEV-431 request rate limit

- doc/UseCases/uc-ss_x-road_use_case_model_for_security_server_management_1.4_Y-883-4.md
…_Y-883-4.md
- Changed terminology: "internal TLS certificate" to "security server's TLS certificate"
- Added in UC 3.12 UC SS: Request TLS certificate and Import TLS certificate UC 3.12 UC SS\_11: Generate a new TLS Key and Certificate for the Security Server
Please include a summary of the change
> XRDDEV-347 -  Managing different types of keys
